### ISSUE TITLE
Purescript 15.0 support

### ISSUE THREAD

**Issue by prescientmoon** [slamdata/purescript-halogen-bootstrap#23]
Hi! Are there any plans to upgrade this to the latest purescript version?

Thanks in advance!

**Comment by garyb** [comment]
No plans no, I should probably mark this repo as deprecated/archived. Is Bootstrap 3 actually what you're working with? There is a link in the readme to a repo for BS4... but maybe that's old too now, I don't actually know what the latest version is anymore. :wink:

Having said that, it's basically just a bunch of `ClassName` defs, so I could do the update trivially if this is all you need. Let me know!

**Comment by prescientmoon** [comment]
Oh, I think this is the wrong repo! :sweat_smile: I'm actually using the library for bootstrap4, I think. I just clicked on the first google result when trying to figure out why I couldn't upgrade to purescript 15.0 :sweat_smile: 

Sorry for the inconvenience, will close this!
